In [2]:
import tensorflow as tf
import numpy as np

In [3]:
# find the version of tensorflow
print(tf.__version__)

# check if tf is using GPU
print("Num GPUs Available: ", len(tf.config.experimental.list_physical_devices('GPU'))) # 0 means no GPU is used

2.10.1
Num GPUs Available:  1


# Learning the basics of tensorflow - from BOOK

In [4]:
# 1. Tensor: multi-dimensional array (also can hold scalar vals) which flow from operation to operation, hence the name TensorFlow
# create a tensor using tf.constant

tf.constant([[1, 2, 3], 
             [4, 5, 6]])

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]])>

In [5]:
# scalar tensor
tf.constant(42) # scalar tensor

<tf.Tensor: shape=(), dtype=int32, numpy=42>

In [6]:
# 2. Indexing tensors
t = tf.constant([[1, 2, 3],
                [4, 5, 6]])
t[:, 1:] # all rows, all columns except the first column


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[2, 3],
       [5, 6]])>

In [7]:
t[..., 1, tf.newaxis] # all rows(...), second column(1), but with an extra dimension(newaxis)

<tf.Tensor: shape=(2, 1), dtype=int32, numpy=
array([[2],
       [5]])>

In [8]:
# 3. Operations on tensors
# addition
print("addition") 
print(t+10)  # equals to tf.add(t, 10)

# multiplication
print("\nmultiplication")
print(t*10) # equals to tf.multiply(t, 10)

# squaring
print("\nsquaring")
print(tf.square(t)) # equals to t*t

# transpose
print("\ntranspose")
print(tf.transpose(t)) 

# other operations
# tf.square, tf.sqrt, tf.exp, tf.log, tf.matmul, tf.reduce_mean, tf.reduce_sum, tf.argmax

addition
tf.Tensor(
[[11 12 13]
 [14 15 16]], shape=(2, 3), dtype=int32)

multiplication
tf.Tensor(
[[10 20 30]
 [40 50 60]], shape=(2, 3), dtype=int32)

squaring
tf.Tensor(
[[ 1  4  9]
 [16 25 36]], shape=(2, 3), dtype=int32)

transpose
tf.Tensor(
[[1 4]
 [2 5]
 [3 6]], shape=(3, 2), dtype=int32)


In [9]:
# 4. similar numpy operations
# we have tf.reshape, tf.squeeze, tf.tile, tf.reduce_mean, tf.reduce_sum, tf.reduce_max, tf.argmax, tf.argmin, tf.math.log

# tf.reduce_sum() - sums all elements in a tensor, its gpu implementation uses a reduce algorithm that does not guarantee the order of the elements.
t_sum = tf.reduce_sum(t, axis=0) # sum along the columns
print(t)
print("\nsum along the columns")
print(t_sum)

tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)

sum along the columns
tf.Tensor([5 7 9], shape=(3,), dtype=int32)


In [10]:
# 5. tensorflow and numpy - they play beautifully together

# np array to tensor
np_array = np.array([1, 2, 3])
tensor = tf.constant(np_array)
print("\nnp array to tensor")
print(tensor)

# tensor to np array
np_array = np.array(tensor)
print("\ntensor to np array")
print(np_array)


np array to tensor
tf.Tensor([1 2 3], shape=(3,), dtype=int32)

tensor to np array
[1 2 3]


In [11]:
# NOTE: Numpy uses 64-bit precision by default, while TensorFlow uses 32-bit. This is because 32-bit precision is more than enough for neural networks, plus it runs faster and uses less memory.

# NOTE: Tensor datatype is immutable - can't be modified after creation. So, we need to use other type for weights and biases in neural networks.

In [12]:
# 6. Type conversions
# you can't perform operations on tensors with different datatypes
# tf.cast() - converts the datatype of a tensor

# tf.constant(2.) + tf.constant(40) # this will throw an error

t1 = tf.constant(2.)
t2 = tf.constant(40)
# convert the int tensor to float
t1 + tf.cast(t2 , dtype=tf.float32) # this will work

<tf.Tensor: shape=(), dtype=float32, numpy=42.0>

In [13]:
# 7. Variables
# variables are mutable tensors that can be changed in place using assign() method.

var = tf.Variable([[1., 2., 3.], [4., 5., 6.]])

# assign a new value to a variable
var.assign(29*var)
print("\nvariable after assign")
print(var)

# assign_add() and assign_sub() methods
var.assign_sub([[1, 1, 1], [1, 1, 1]])
print("\nvariable after assign_sub")
print(var)

var.assign_add([[1, 1, 1], [1, 1, 1]])
print("\nvariable after assign_add")
print(var)


variable after assign
<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[ 29.,  58.,  87.],
       [116., 145., 174.]], dtype=float32)>

variable after assign_sub
<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[ 28.,  57.,  86.],
       [115., 144., 173.]], dtype=float32)>

variable after assign_add
<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[ 29.,  58.,  87.],
       [116., 145., 174.]], dtype=float32)>


In [14]:
# scatter_nd_update() - updates specific elements of a tensor
# give the indices of the elements to update and the new values

t = tf.Variable([[1, 2, 3], [4, 5, 6]])
t.scatter_nd_update(indices=[[0, 0], [1, 2]], updates=[100, 200])

<tf.Variable 'UnreadVariable' shape=(2, 3) dtype=int32, numpy=
array([[100,   2,   3],
       [  4,   5, 200]])>